### ISSUE TITLE
Should I write tests for this method? (Since it is very short)

### ISSUE THREAD

**Issue by fuiszgt** [googleinterns/step234-2020#21]
https://github.com/googleinterns/step234-2020/blob/fd4bcd45bb09d26ee38ecb83d9719128be2ced76/src/main/java/com/google/sps/servlets/ScheduleServlet.java#L66

**Comment by dola** [comment]
yes! But to make it easier to test, change the signature to get all tasks and the taskIds to schedule instead of the whole request. This method shouldn't have to know how to extract anything from
