### ISSUE TITLE
Use JavaScript templates to render HTML

### ISSUE THREAD

**Issue by fuiszgt** [googleinterns/step234-2020#46]

**Comment by dola** [comment]
Some options:
 - templates in HTML
 - all in JS (current)
 - templating engine
   - Handlebars
   - Mustache
   - [List of Engines](https://colorlib.com/wp/top-templating-engines-for-javascript/)

**Comment by Giost** [comment]
Previous PR discussion: https://github.com/googleinterns/step234-2020/pull/41#discussion_r484386285
