### ISSUE TITLE
[Branch: set-working-hours] A second circular progress indicator appears and is orbiting around the first one.

### ISSUE THREAD

**Issue by fuiszgt** [googleinterns/step234-2020#53]
On set-working-hours branch, there is a problem with the circular progress indicator:
![Screenshot 2020-09-23 at 1 30 39 PM - Display 2](https://user-images.githubusercontent.com/6977732/94007730-2e355d80-fda2-11ea-8991-0c137555931d.png)

**Comment by fuiszgt** [comment]
This is possibly related to the auto-reformat performed on the index.html, in particular the changes made to the html of the progress indicator. https://github.com/googleinterns/step234-2020/pull/51/files#diff-9c62375b78aa4485aac0227f0537077c

**Comment by zlorf** [comment]
Looking into it

**Comment by zlorf** [comment]
From https://material.io/develop/web/components/circular-progress:
`IMPORTANT: Do not introduce space between the adjacent </div><div> tags above. Doing so will produce unwanted visual artifacts.`
You're correct, the auto-formatter is responsible for the problem. I've checked the bringing the divs on the same line fixes the problem.
Now, the question is how to allow for auto-formatting while preserving this "exception"?

**Comment by zlorf** [comment]
First thing first: this is a very bad design of material.io component, that such a whitespace might break everything.
A CSS fix for this (while keeping any HTML structure) is to add
`.mdc-circular-progress__spinner-layer { font-size: 0; }` to styles
